version: '3'
services:
  db:
    container_name: sample_app_db
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      PGDATA: /temp
#      POSTGRES_DB: myapp_development
      POSTGRES_PASSWORD: secret
  web:
    container_name: sample_app_web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
